### ISSUE TITLE
Reader renders users outbox as feed

### ISSUE THREAD

**Issue by sutty-coop** [hyphacoop/distributed-press-organizing#117]
Read from users outboxes into a feed (0.5 week)
- Read staticpub inbox to start, have interface that takes a "num posts" and "page" param and has an async iterator of Activities.
- Handle create/update/

Check the boxes from #102 when this is done 👍

**Comment by RangerMauve** [comment]
- add a new `distributed-outbox` component
- have url to outbox as an attribute
- add a new `distributed-activity` which will render different activity types
- it should call out to distributed-post for created notes
- other types can be ignored for now but maybe we'd want to show follow requests and likes too
- have the outbox fetching method return an async iterator (using an async generator function) so that we can refactor it more easily for different outbox setups.
