### ISSUE TITLE
Update jekyll plugin with p2p

### ISSUE THREAD

**Issue by sutty-coop** [hyphacoop/distributed-press-organizing#121]

**Comment by fauno** [comment]
This means jekyll-activity-pub adds support for the #103 right?

**Comment by sutty-coop** [comment]
We wait for the draft of #115 and push this issue to Feb 15

**Comment by RangerMauve** [comment]
Yup! Here's how:

We need to track multiple domains for ActivityPub instead of just the one https domain.
This will have the ipfs/hyper/etc prefixes.
We will need to generate AP files per domain. Maybe we could add a suffix like `actor.0.ldjson`, `actor.1.ldjson`.
We will need to have each object have an `alsoKnownAs` field that links to the url of the object with the other domain prefix. E.g. something with an https url will link to their ipns version.

This also means we might need to modify the webfinger code to somehow handle the multiple "identities". Maybe all of the urls can be in there with https first and then non-p2p clients might ignore them?

Same with HTML files, we'll need to link to all the versions of the ap files with the appropriate urls.

**Comment by fauno** [comment]
Regarding [FEP fffd](https://codeberg.org/fediverse/fep/src/branch/main/fep/fffd/fep-fffd.md) I checked Mastodon's code and when it finds that the `url` attribute of an activity/actor is an array of objects, it'll pick the first one with `mimeType` equal `"text/html"` and ignore the rest.

So if we list the HTTPS versions first, anything that comes afterwards should be compatible, even if it's the HTML version on IPFS.

**Comment by fauno** [comment]
@sutty-coop this isn't finished though

**Comment by RangerMauve** [comment]
Done!
