### ISSUE TITLE
Backend - Add clone API

### ISSUE THREAD

**Issue by RangerMauve** [hyphacoop/distributed-press-organizing#199]
- [x] sketch HTTP API for front end team
- [x] port wget code to a syscall
- [x] add HTTP API
- [x] Staging test
- [ ] Prod test
- [ ] Docs

**Comment by fauno** [comment]
@RangerMauve one of the steps is to add the domain, ask the user to create an NS record on their DNS and wait for the record to resolve properly, do I do this on the browser with doh? I'm looking at [dohjs](https://github.com/byu-imaal/dohjs)

also i can check the NS record is set properly, but i wonder if i should be checking something on api.distributedpress.org  would be a better second-step check, for instance, issuing these queries:

```
NS _dnslink.usersdoma.in ; => should resolve to "api.distributed.press."
TXT _dnslink.usersdomain.in ; => should query api.distributed.press.
```

since the domain won't be created yet, DP's DNS server could maybe respond with a "yeah i'm working just get a token" and a very short TTL. too much work?

**Comment by RangerMauve** [comment]
Lets do the DOH check in the front end to start.

> since the domain won't be created yet, DP's DNS server could maybe respond with a "yeah i'm working just get a token" and a very short TTL. too much work?

Do you mean this should happen when we try to create a site? I think it should be okay to try to create sites with invalid DNS personally for offline use cases or when you want a p2p site just for p2p URLs that'll never resolve via DNS. I guess we could enforce it just for trial tokens though? IS the goal just to avoid people cloning sites they don't "own"?

**Comment by fauno** [comment]
> IS the goal just to avoid people cloning sites they don't "own"?

i would want to center user consent in things we do and avoid getting complaints because someone suddenly discovers their website on distributed press, unless we start branding as the distributed internet archive (!)

**Comment by RangerMauve** [comment]
Cool so what if we have this check just for the clone API and keep the rest as is?

**Comment by RangerMauve** [comment]
This'd also mean we can't demo cloning unless we get the potential client to set up their DNS first which is less fun.

**Comment by RangerMauve** [comment]
Had a call today to discuss this.
- we'll leave the api as is without the check for now
- this will make it easier to do demos where we clone sites for potential clients
- if it becomes an issue we'll add the check
