### ISSUE TITLE
Settle on Social Integration Moderation Strategy

### ISSUE THREAD

**Issue by RangerMauve** [hyphacoop/distributed-press-organizing#77]
🎟️ **Re-ticketed from:** #  
📅 **Due date:** N/A  
🎯 **Success criteria:** ...  

## Task Summary

...

## To Do

- [ ] ...

**Comment by RangerMauve** [comment]
Wrote a bit of a thread on this here: https://mastodon.mauve.moe/web/@mauve/110300317077369839

**Comment by fauno** [comment]
Some notes on what we've discussed at Sutty:

* Non moderation is undesirable, we don't want to expose visitors and users to hate speech attacks, either by publishing stuff as-is, or asking users to keep up with a moderation queue and having to read hateful stuff
* Supporting blocklists/allowlists enables blocking undesirable instances wholesale instead of doing piecemeal moderation. They can also be shared/reused between sites.
* Undecided on blocklists vs allowlists, if we support both, it should be a conscious decision for users when they enable social features (vs opt-in/opt-out).
* Undecided if we can/want to maintain lists/moderate the whole CMS (Sutty as a fediverse instance vs Sites as fediverse instances)
* Undecided if collective moderation should be a feature --lists are shared on the same CMS instance and all users are welcome to help.
* Would be good to have an all-hands session where we only discuss about moderation.  Invite people to a second session.

**Comment by RangerMauve** [comment]
We're going to have a call some time to get folks to talk about these tradeoffs.

The goal will be to get us all on the same page on what we value in the moderation and what we're going to implement.

**Comment by RangerMauve** [comment]
TODO for me: We have a strategy now, I'll post it in detail here.

**Comment by RangerMauve** [comment]
So, here's what we'll be settling on for the moderation:

- Our Social Inbox server will be the core of how we do moderation.
- By default any incoming interactions will go through a "moderation queue"
- Publishers will be able to manually approve follow requests and eventually replies
- Block lists will be useable for specific users or entire instances to auto-deny anything incoming
- Allow lists will be used for specific users or entire instances to auto-allow anything incoming
- We will supply a default block-list of some of the most blocked instances on the fediverse so that by default you can avoid a large community of trolls/harassers
- We will have instance-wide block-lists and allow-lists which we will configure for people signing up with the Hypha-run instance, and other instances will be encouraged to curate their own.
- We will also enable publishers to have seperate block lists and allow lists for their individual inboxes so that they can block or allow users/instances outside of the default rules.
- The APIs will have the ability to block add/remove items using newline delimited strings
- We will have webhooks that can send notifications to whatever service you have whenever a new moderation item is in place so you can integrate it into your own in-house moderation pipelines.
- We will provide [Swagger](https://swagger.io/) definitions and this will also act as the default User Interface for using the moderation API.
- Folks can make their own interfaces using whatever languages they want and any interfaces we make in addition to this will also be published as open source
- The [Sutty CMS](https://panel.sutty.nl/) will be integrating user interfaces for our moderation APIs for folks that want an "out of the box" solution

One thing on the TODO list is to have block-lists of words to enable filtering out slurs / dog whistles to ease automation further, but there's no timeline for when we'll have that.

We'll be making use of these moderation features for our Hypha / COMPOST specific blogs as a way to test out the usability and we'll be adding/removing stuff to make it easier for us and anyone else making use of the tool.

If you have any thoughts or questions feel free to post them here or ping me [on the fediverse](https://mastodon.mauve.moe/@mauve).

**Comment by RangerMauve** [comment]
I think we should base our initial blocklist on https://thebad.space/about

This seems to cover a lot of forms of bigotry or low-moderation instances.

This list is pretty strict and blocks large instances like mastodon.social

https://thebad.space/location/aac50add-0024-49fb-9096-27db308d3842

We might want to discuss whether we want to manually add exceptions with a tradeoff of getting more reach at the expense of safety.

**Comment by RangerMauve** [comment]
We will also default to using the [garden fence](https://github.com/gardenfence/blocklist/blob/main/gardenfence-mastodon.csv) blocklist in order to ease onboarding to the fediverse by preemptively blocking the least safe instances.
